# Generated by Django 5.2.3 on 2025-06-15 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatHistory',
            new_name='Chat',
        ),
    ]
