# Generated by Django 5.2.3 on 2025-06-15 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0002_rename_chathistory_chat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='ChatHistory',
        ),
    ]
