# Generated by Django 5.2.3 on 2025-06-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0004_chathistory_polarity_chathistory_subjectivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='model_used',
            field=models.CharField(choices=[('gemini', 'Gemini Pro'), ('dialogpt', 'DialoGPT'), ('rule_based', 'Rule-Based')], default='gemini', max_length=20),
        ),
    ]
